[package]
name = "rustyline"
version = "1.0.0"
authors = ["Katsu Kawakami <kkawa1570@gmail.com>"]
description = "Rustyline, a readline implementation based on Antirez's Linenoise"
documentation = "http://docs.rs/rustyline"
repository = "https://github.com/kkawakam/rustyline"
readme = "README.md"
keywords = ["readline"]
license = "MIT"
categories = ["command-line-interface"]

[badges]
travis-ci = { repository = "kkawakam/rustyline" }
appveyor = { repository = "kkawakam/rustyline" }

[dependencies]
libc = "0.2"
log = "0.4"
unicode-width = "0.1"
unicode-segmentation = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.10"
term = "0.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "handleapi", "minwindef", "processenv", "winbase", "wincon", "winuser"] }

[dev-dependencies]
tempdir = "0.3"
